# This is a config for E2B sandbox template.
# You can use template ID (5zo9pxyfrs0106j84te8) or template name (vibe-nextjs-test-9900) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-test-9900") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-9900") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-9900')

team_id = "495d1602-efc4-47c3-b7af-51fe532618d6"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-9900"
template_id = "5zo9pxyfrs0106j84te8"
